# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
